[IV-24-25] Objetivo_0_FabriConde
FabriConde/IV-2024-2025 pull request #1
Opened 2024-09-20 11:14 UTC by FabriConde

Pull request para la entrega del Objetivo_0

2024-09-20 11:51 UTC, JJ requested changes
Por, favor, lee los comentarios.

2024-09-20 11:51 UTC, JJ commented on README.md
> +> DESARROLLADOR
No hace falta que incluyas el desarrollador. Tienes que describir solo el problema del cliente.

2024-09-20 11:51 UTC, JJ commented on README.md
> +> VALIDACIÓN
Esto es más en el cuerpo del PR que en README.

2024-09-20 12:07 UTC, FabriConde commented
@JJ Listo para revisar

2024-09-22 10:24 UTC, JJ commented
Por favor, lee y pasa [la lista de comprobación](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#lista-de-comprobaci%C3%B3n), que me ayuda a la hora de revisar para saber si has tenido en cuenta todo lo que ahí se dice e indicarte puntualmente qué es lo que no se ha hecho. Cuando lo hagas pasaré a revisar el contenido.

2024-09-22 18:44 UTC, FabriConde commented
@JJ Se ha añadido lista de comprobación al PR y actualizado el README

2024-09-22 18:57 UTC, JJ requested changes
Por favor, consulta en [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#en-el-contenido):

> Si de describe lo que el cliente quiere hacer sin decir por qué quiere hacerlo, no estás describiendo el problema, estás describiendo una solución. Es imposible de esa fomra solucionar el problema.

En este objetivo, como en el resto de la asignatura, conviene que entiendas por qué estás haciendo esto y por qué es necesaria una precisión y un contenido determinado.

2024-09-22 18:57 UTC, JJ commented on README.md
> +Soy un escalador y tengo el siguente problema: Quiero ver las zonas de escalada que hay por mi zona ya que no hay información sobre ello en Internet y es necesario saber el grado de las vías que se v
Esto ya lo hablamos en clase. No estás describiendo un problema, estás describiendo una solución. Además, lo dejaste escrito. 
Recuerda que te pregunte por qué querías ver las zonas de escalada. También hablamos de qué tipo de cliente eras y demás. 
De veras, si no hacéis lo que se estuvo hablando con la máxima precisión es imposible seguir adelante para construir un proyecto sobre esto. ¿Te parece que con la frase que has escrito sea suficiente para comenzar a trabajar en un proyecto?

2024-09-22 18:58 UTC, JJ commented
> # Pull request para la entrega del Objetivo_0
> 
> > DESARROLLADOR
> 
>     * El escalador quiere ver la zonas de escalada para ir los fines de semana que se adapte a su nivel
> 
>     * Por ahora hay poca información y si la hay está en wikiloc
> 
> 
> > Lista de comprobación
> 
>     * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Si, soy escalador
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
>       Si, para que la gente puede buscar información en todo momento
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
>       Si, tiene que tener acceso a una base de datos

Entonces no es una buena solución. Necesita que tenga una cierta lógica de negocio.
> 
>     * [x]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
>       `README`?
>       Si
> 

¿Dónde la has enlazado?

2024-09-24 22:26 UTC, FabriConde commented
Revison @JJ

2024-09-25 05:57 UTC, FabriConde commented
Revisión @JJ

2024-09-25 06:01 UTC, FabriConde commented
Revisión @JJ

2024-09-25 06:35 UTC, JJ requested changes
Has hecho una parte de la configuración que comenta [aquí](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n), pero no has hecho o no has documentado otra parte. Te rogaría que lo hicieras.

2024-09-25 06:35 UTC, JJ commented on README.md
> +Como escalador me hallo con el problema de la falta de información que hay de los sectores de escalada en Granada. Buscando por Internet me he dado cuenta de que los croquis que existen están muy des
¿Entiendo que la solución en la que estás pensando es procesamiento de imagen?
Te recuerdo que toda la lógica de negocio tienes que programarla tú. en [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n) pone:

> En este objetivo no se pide que se especifique la solución al problema. Sin embargo, sí habrá que hacerlo más adelante y si se trata de un problema cuyas posibles soluciones no sean válidas para esta asignatura, se rechazará en este objetivo. 

Si no es esa la solución en la que estás pensando, por favor acláralo; en este objetivo, aunque en general no hay que especificar la solución, en caso de que dependa de qué solución se trate para que sea válida conviene que lo hagáis.

2024-09-25 11:38 UTC, FabriConde commented on README.md
> +Como escalador me hallo con el problema de la falta de información que hay de los sectores de escalada en Granada. Buscando por Internet me he dado cuenta de que los croquis que existen están muy des
@JJ 
No sé muy bien a lo que te refieres con esto:  Creación de par de claves (pública/privada) y subida de clave pública a GitHub. ¿La creación de par de claves (pública/privada) es crear SSH Keys? Es que no conozco muy bien los terminos  de GitHub
Por otro lado, en respuesta a esto: ¿Entiendo que la solución en la que estás pensando es procesamiento de imagen?
Si, la solución sería que la lógica de negocio procesara la imagen (conversión de las imagines a bytes para almacenarlas en base de datos y viceversa)

2024-09-25 15:15 UTC, JJ commented on README.md
> +Como escalador me hallo con el problema de la falta de información que hay de los sectores de escalada en Granada. Buscando por Internet me he dado cuenta de que los croquis que existen están muy des
> @JJ No sé muy bien a lo que te refieres con esto: Creación de par de claves (pública/privada) y subida de clave pública a GitHub. ¿La creación de par de claves (pública/privada) es crear SSH Keys?

keys significa claves. 

> Es que no conozco muy bien los terminos de GitHub

No son de GitHub, es la forma estándar de hacer conexiones remotas. Es algo imprescindible aquí y que podéis aprender rápidamente.

> Por otro lado, en respuesta a esto: ¿Entiendo que la solución en la que estás pensando es procesamiento de imagen? Si, la solución sería que la lógica de negocio procesara la imagen (conversión de las imagines a bytes para almacenarlas en base de datos y viceversa)

Salvo que vayas a escribir tú el código completo que procese la imagen, y como te he comentado más arriba, no sería una solución que se pueda abordar en esta asignatura. El objetivo de que escribáis vosotros el código es que aprendáis a hacerlo según especificaciones y a hacer tests de caja blanca (es decir, donde se conozca y se testee todo el código bajo prueba)

2024-09-25 16:00 UTC, FabriConde commented on README.md
> +Como escalador me hallo con el problema de la falta de información que hay de los sectores de escalada en Granada. Buscando por Internet me he dado cuenta de que los croquis que existen están muy des
@JJ 
Ya he añadido la creación de par de claves (pública/privada)  a la carpeta Documentación.

2024-09-25 16:07 UTC, FabriConde commented on README.md
> +Como escalador me hallo con el problema de la falta de información que hay de los sectores de escalada en Granada. Buscando por Internet me he dado cuenta de que los croquis que existen están muy des
>  Salvo que vayas a escribir tú el código completo que procese la imagen, y como te he comentado más arriba, no sería una solución que se pueda abordar en esta asignatura. El objetivo de que escribáis vosotros el código es que aprendáis a hacerlo según especificaciones y a hacer tests de caja blanca (es decir, donde se conozca y se testee todo el código bajo prueba)

Entonces me olvido del procesado de imagenes, con que sepa la dirección donde están los sectores de escalada y el numero de vías y sus grados me sirve. El poder mostrar imagenes es para que sea algo más visible, pero sin las imagenes el problema se resuleve igual.

2024-09-25 16:48 UTC, JJ commented on README.md
> +Como escalador me hallo con el problema de la falta de información que hay de los sectores de escalada en Granada. Buscando por Internet me he dado cuenta de que los croquis que existen están muy des
OK, específicalo bien en el documento.

2024-09-25 16:49 UTC, JJ commented
En este primer objetivo no pasa nada porque subáis ficheros desde la web pero *realmente* tenéis que aprender a usar git en la línea de órdenes (no cliente)

2024-09-25 21:19 UTC, FabriConde commented
Revisión @JJ

2024-09-26 05:42 UTC, JJ requested changes
Es esencial una adecuada descripción del problema.

2024-09-26 05:42 UTC, JJ commented on README.md
> +Como escalador me hallo con el problema de la falta de información que hay de los sectores de escalada en Granada. Buscando por Internet me he dado cuenta de que los croquis que existen están muy des
Debes modificar el texto sobre el que se haga el comentario o bien resolver el issue indicando dónde se ha hecho el cambio correspondiente.

2024-09-26 05:42 UTC, JJ commented on README.md
> +Para resolver este problema vamos a visualizar en una pantalla las direcciones de los sectores de escalada, dentro de cada dirección se mostrará el número de vías y el grado de cada vía que hay por s
Esta solución no tiene nada que ver con el problema, que sigue hablando solamente de "croquis". Como indica en [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio):
> En este objetivo no se pide que se especifique la solución al problema. Sin embargo, sí habrá que hacerlo más adelante y si se trata de un problema cuyas posibles soluciones no sean válidas para esta asignatura, se rechazará en este objetivo. Por eso hay que pensar en la solución al problema, y en caso de que no quede claro su entidad

El problema sigue estando sin especificar, ya que lo único que dice es que "los escaladores hacen croquis", y sigue centrándose en los mismos.

2024-09-26 07:06 UTC, FabriConde commented
@JJ Revisión

2024-09-26 07:17 UTC, FabriConde commented
@JJ Revisión

2024-09-26 07:39 UTC, FabriConde commented
@JJ Revisón

2024-09-26 08:10 UTC, JJ requested changes
Como siempre, la cuestión fundamental es que tienes no sólo que describir un problema, sino que te sirva para la asignatura. Consulta por favor los [errores frecuents](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#sobre-el-código-definido) y trata de especificar claramente cómo se encuentran esas instrucciones de escalada y qué es lo que habría que hacer para procesarlas. Puede que se trata de información poco estructurada o semiestructurada, cuya extracción podía ser el problema específico a resolver.

2024-09-26 08:10 UTC, JJ commented on README.md
> +Para resolver este problema vamos a visualizar en una pantalla las direcciones de los sectores de escalada, dentro de cada dirección se mostrará el número de vías y el grado de cada vía que hay por s
Como os he comentado, la solución al problema hay que comentarla en caso de que no esté claro por la descripción del mismo. Pero en ese caso tienes que indicar realmente qué pasos vas a hacer para resolverlo, dentro de los límites de esa asignatura, no qué vas a haceer para mostrar el problema resuelto. "Visualizar en una pantalla" no es una solución, sino que es una visualización de una solución. Y no se parece en nada a algo que haya que hacer en esta asignatura.

2024-09-26 08:10 UTC, JJ commented on README.md
> +La lógica de negocio procesará esta información calculando estadísticas sobre los sectores de escalada, como el número promedio de vías por sector o el grado de dificultad predominante, generando map
¿De dónde saca los sectores de escalada?
¿Será extraer los sectores de escalada de información poco estructurada el problema específico que tienes que resolver?

2024-09-26 17:42 UTC, JJ approved these changes
Corrige lo comentado antes de mergear, por favor. O después, pero que esté corregido para el objetivo siguiente.

2024-09-26 17:42 UTC, JJ commented on README.md
> +La lógica de negocia será capaz de extraer mediante un texto la información que se le ha proporcionado, se extraera ubicación, sector, número de vías y nombre y grado de cada vía.
Esto no es la solución, es el contexto del problema. Si "es capaz de extraerlo" es porque existe esa información en algún lado, ¿no?

2024-09-26 18:35 UTC, FabriConde commented on README.md
> +La lógica de negocia será capaz de extraer mediante un texto la información que se le ha proporcionado, se extraera ubicación, sector, número de vías y nombre y grado de cada vía.
Ok, lo quito del README.md

2024-09-27 10:37 UTC, merged