Objetivo 1
FabriConde/IV-2024-2025 pull request #4
Opened 2024-09-29 15:45 UTC by FabriConde

# Sobre las historias de usuario

* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

# Sobre los milestones

* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x] ¿El milestone 0 es mínimo *y* viable?
* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

2024-10-01 07:32 UTC, juanmaaf reviewed
Buenas, se me ha asignado revisar tu PR. Basándome en la lista de comprobación, he realizado un par de observaciones, pero generalmente se ve correcto.

2024-10-01 07:32 UTC, juanmaaf commented on README.md
> +#### [[HU001] Obtener información general de un sector de escalada](https://github.com/FabriConde/IV-2024-2025/issues/2)
Las historias de usuario están bien definidas, acompañadas de un user journey que las aclara. No está mal enlazar directamente al issue del repositorio, pero podrías plantearte crear un documento en el directorio docs donde se incluya la explicación de todas las historias de usuario.

2024-10-01 07:32 UTC, juanmaaf commented on README.md
> +#### [[M0] : Modelado de la lógica de negocio](https://github.com/FabriConde/IV-2024-2025/milestone/1)
Los milestones están bien estructurados y definen un producto mínimo. Sin embargo, respecto al milestone 0, indicando que vas a diseñar un modelo MVC estás proponiendo una solución. La metodología de desarrollo ágil indica que irás descubriendo poco a poco la solución al problema inicial. Al igual que he mencionado en el caso de las historias de usuario, podría ser una buena idea tener la explicación de todos los hitos en un único documento. Por último, no se indica cómo comprobar la viabilidad en cada hito.

2024-10-01 08:20 UTC, antoniorr02 reviewed
En general lo veo todo correcto y no tengo nada que añadir a las recomendaciones de mi compañero @juanmaaf, a parte de la que he añadido.

2024-10-01 08:20 UTC, antoniorr02 commented on README.md
> +#### [[M1] Funcionalidades Básicas de búsqueda y filtrado](https://github.com/FabriConde/IV-2024-2025/milestone/2)
Tal vez deberías de comenzar con un hito 1 menos complejo, ya que en el modelo PVM se busca desarrollar un producto simple de forma rápida y me parece que este hito abarca demasiadas cosas (localizar en el mapa, filtrar las localizaciones, incluir la información relativa, etc). En el PVM se busca una fase incial simple en la cual ir escalando y añadiendo mejoras incrementales, me da la sensación de que en este hito abarcas la aplicación completa. Por lo demás no tengo nada más que añadir a mi compañero.

2024-10-01 08:34 UTC, giorgiogiovanni requested changes
Buenas, me asignaron para revisar tu PR.

Como pequeña nota general. El problema no es que los escaladores locales son los que tienen la información, sino el acceso a esa información por escaladores foráneos.

2024-10-01 08:34 UTC, giorgiogiovanni commented on docs/user journey.md
> +- Se acaba de mudar a Vélez-Rubio y quiere escalar en su tiempo libre, pero al no conocer a nadie que escale no tiene información de los sectores de la zona.
El user journey pretende ser un viaje por la experiencia del usuario. Es decir, describe como interactuaría el usuario con el sistema. En este caso se describe al usuario pero no la interacción del mismo, está bien contextualizado, pero debería indicar precisamente qué experiencia tiene dicho usuario mientras utiliza la aplicación.

2024-10-01 08:34 UTC, giorgiogiovanni commented on README.md
>  > Especificación de la solución del problema
Revisa los titulos. El _design thinking_ es un método de encontrar la solución. Considera no decir que especificas ya la solución, sino que estás describiendo el problema en profundidad.

2024-10-01 08:34 UTC, giorgiogiovanni commented on README.md
> +## OBJETIVO 1
De igual forma, yo evitaría utilizar las referencias a los objetivos y especificaría en general secciones con titulos explicativos: descripcion del problema, planificacion del proyecto, etc

2024-10-03 07:32 UTC, FabriConde commented
Revisión @giorgiogiovanni @antoniorr02  @juanmaaf

2024-10-03 08:17 UTC, FabriConde commented
Revisión @giorgiogiovanni @antoniorr02 @juanmaaf

2024-10-03 10:39 UTC, antoniorr02 approved these changes

2024-10-03 10:40 UTC, juanmaaf approved these changes

2024-10-03 11:09 UTC, giorgiogiovanni approved these changes
En general me parece correcto.

Solo como nota, creo que ambos user journeys expresan exactamente el mismo deseo, simplemente es un contexto de usuario distinto, pero ambos tienen exactamente la misma experiencia a la hora de ver utilizar la aplicación.

2024-10-03 15:35 UTC, FabriConde commented
Revisión @JJ

2024-10-03 17:38 UTC, JJ requested changes
Está bastante bien y agradezco a los comentadores su trabajo, pero creo que quedarían algunos pequeños detalles que perfeccionar. Con eso, listo.

2024-10-03 17:38 UTC, JJ commented on README.md
> +#### [M0] Diseño del modelo de datos
El modelo de datos no se diseña, se resuelve.

2024-10-03 17:38 UTC, JJ commented on README.md
> +#### [M1] Implementación de la lógica
Deberíais intentar formular los milestones no como tareas, sino como productos. Una implementación se termina y ya está, no hay nada implícito sobre qué la hace válida. Si describes un producto, al menos se tiene cierta indicación sobre qué se está buscando.

2024-10-03 17:38 UTC, JJ commented on README.md
> +#### [M2] Almacenamiento y recuperación
Realmente es irrelevante, pero en esta asignatura no se le va a dar mucha importancia a la serialización, sino más bien a la publicación en un API. En todo caso te digo lo mismo que antes: si no dices qué producto quieres tener con ese almacenamiento y recuperación, es pierde bastante información.

2024-10-03 17:38 UTC, JJ commented on docs/milestones.md
> +- **Objetivo**: Diseñar la estructura de datos para almacenar la información a extraer de los textos.
¿De qué historias de usuario estamos hablando?

2024-10-03 17:38 UTC, JJ commented on docs/milestones.md
> +- **Viabilidad**: Cuando lo validen los revisores o el profesor.
Esta definición es redundante. Piensa en negativo: ¿qué pasa si el profesor dice que está mal? Si no añades algún otro criterio de viabilidad que lo haga más objetivo, no es practicable.

2024-10-03 17:38 UTC, JJ commented on docs/milestones.md
> +- **Viabilidad**: Cuando pasen los tests.
Los tests escritos ¿según qué historias de usuario? ¿Todas? ¿La primera? ¿Las dos primeras?

2024-10-04 12:22 UTC, FabriConde commented
Revisión @JJ

2024-10-04 15:33 UTC, JJ commented on docs/milestones.md
> +- **Viabilidad**: Las relaciones entre las entidades deben ser implementadas de forma que reflejen con precisión la realidad del problema.
Tienes dos historias de usuario. ¿La realidad es de los dos o de una sola? ¿Tanto trabajo cuesta indicar claramente en qué es en lo que tiene que trabajarse en el objetivo 2?

2024-10-06 17:33 UTC, FabriConde commented
Revisión @JJ

2024-10-06 17:52 UTC, JJ commented
ya está revisado y aprobado. Gracias por hacer los cambios.

2024-10-06 18:01 UTC, merged

2024-10-06 18:02 UTC, JJ commented
Y el proyecto no se llama IV-2024-2025. Ponle al repo un nombre correcto.